export type SeedAssumption = {
  seedKey: string; // format: "a001", "a002", ... "a112"
  statement: string;
  category: string;
  importance: "critical" | "high" | "medium" | "low";
  confidence: "low" | "medium" | "high" | "proven";
  nextAction: string;
};

export const CATEGORIES = [
  "Problem & Market",
  "Customer",
  "Capacity Engine",
  "Experiment Interaction",
  "Scheduling",
  "Knowledge",
  "AI",
  "Product & Integration",
  "Commercial",
  "Competitive",
  "Founder & Execution",
] as const;

export const SEED_ASSUMPTIONS: SeedAssumption[] = [
  {
    seedKey: "a001",
    statement: "Mature experimentation teams struggle to know their true testing capacity.",
    category: "Problem & Market",
    importance: "critical",
    confidence: "high",
    nextAction: "Interview 10 to 15 experimentation leads and ask how they currently determine available testing capacity.",
  },
  {
    seedKey: "a002",
    statement: "Experiment roadmaps regularly contain more tests than available traffic can support.",
    category: "Problem & Market",
    importance: "critical",
    confidence: "high",
    nextAction: "Obtain real experiment roadmaps and compare planned experiments, available traffic and historical throughput.",
  },
  {
    seedKey: "a003",
    statement: "Teams struggle to predict how long planned experiments will take.",
    category: "Problem & Market",
    importance: "critical",
    confidence: "high",
    nextAction: "Compare planned test duration with actual duration across historical experiment programmes.",
  },
  {
    seedKey: "a004",
    statement: "Test duration is usually considered too late in planning.",
    category: "Problem & Market",
    importance: "high",
    confidence: "high",
    nextAction: "Ask experimentation teams when sample size and expected duration first enter their planning process.",
  },
  {
    seedKey: "a005",
    statement: "Organisations optimise individual experiments but rarely optimise the overall experimentation portfolio.",
    category: "Problem & Market",
    importance: "critical",
    confidence: "high",
    nextAction: "Map how mature experimentation programmes allocate traffic and prioritise competing experiments.",
  },
  {
    seedKey: "a006",
    statement: "Parallel experimentation creates uncertainty about interaction and pollution risk.",
    category: "Problem & Market",
    importance: "high",
    confidence: "high",
    nextAction: "Ask experimentation teams to explain their rules for allowing simultaneous experiments.",
  },
  {
    seedKey: "a007",
    statement: "Fear of interaction causes some organisations to test unnecessarily sequentially.",
    category: "Problem & Market",
    importance: "high",
    confidence: "high",
    nextAction: "Collect examples where experiments were delayed solely because another experiment was running.",
  },
  {
    seedKey: "a008",
    statement: "Some organisations run experiments simultaneously without properly understanding interaction risk.",
    category: "Problem & Market",
    importance: "high",
    confidence: "high",
    nextAction: "Review real experiment calendars and ask teams how interaction risk was assessed.",
  },
  {
    seedKey: "a009",
    statement: "Experiment capacity is a meaningful business constraint, not merely a CRO inconvenience.",
    category: "Problem & Market",
    importance: "critical",
    confidence: "medium",
    nextAction: "Quantify delayed experiments and estimate the commercial opportunity cost created by capacity constraints.",
  },
  {
    seedKey: "a010",
    statement: "Experimentation planning becomes materially harder as organisations add web, app, checkout and server-side testing.",
    category: "Problem & Market",
    importance: "high",
    confidence: "high",
    nextAction: "Compare planning processes between single-platform and multi-platform experimentation teams.",
  },
  {
    seedKey: "a011",
    statement: "Experiment knowledge is fragmented across tools, decks, spreadsheets and people's heads.",
    category: "Problem & Market",
    importance: "critical",
    confidence: "high",
    nextAction: "Ask teams to locate and explain the result and learning from a randomly selected experiment more than 12 months old.",
  },
  {
    seedKey: "a012",
    statement: "Organisations repeatedly test questions they have effectively answered before.",
    category: "Problem & Market",
    importance: "high",
    confidence: "medium",
    nextAction: "Review historical experiment libraries for repeated hypotheses or substantially similar questions.",
  },
  {
    seedKey: "a013",
    statement: "Experiment results are poorly connected to subsequent product decisions.",
    category: "Problem & Market",
    importance: "high",
    confidence: "high",
    nextAction: "Trace product decisions backwards to the experimentation evidence that informed them.",
  },
  {
    seedKey: "a014",
    statement: "Experimentation platforms understand experiments but not enough of the customer's wider business context.",
    category: "Problem & Market",
    importance: "critical",
    confidence: "high",
    nextAction: "Compare major experimentation-platform data models with the contextual information required for portfolio-level planning.",
  },
  {
    seedKey: "a015",
    statement: "Existing experimentation platforms are unlikely to solve the whole orchestration problem themselves.",
    category: "Problem & Market",
    importance: "critical",
    confidence: "medium",
    nextAction: "Track competitor capabilities and roadmaps and test this belief during customer interviews.",
  },
  {
    seedKey: "a016",
    statement: "Heads of Experimentation and CRO are likely to be the initial internal champions for Knomera.",
    category: "Customer",
    importance: "critical",
    confidence: "high",
    nextAction: "Conduct founder-led outreach and track which roles engage most strongly with the proposition.",
  },
  {
    seedKey: "a017",
    statement: "The economic buyer may sit above the experimentation team.",
    category: "Customer",
    importance: "high",
    confidence: "medium",
    nextAction: "Track champion, decision-maker, budget holder and procurement involvement during early sales conversations.",
  },
  {
    seedKey: "a018",
    statement: "Product leaders also care about experimentation capacity.",
    category: "Customer",
    importance: "high",
    confidence: "medium",
    nextAction: "Interview Heads and VPs of Product separately from experimentation specialists.",
  },
  {
    seedKey: "a019",
    statement: "Companies with multiple experimentation teams feel the problem more strongly.",
    category: "Customer",
    importance: "high",
    confidence: "high",
    nextAction: "Compare reported pain and planning complexity by number of teams running experiments.",
  },
  {
    seedKey: "a020",
    statement: "Companies running 50 or more experiments per year are substantially better initial prospects than low-volume programmes.",
    category: "Customer",
    importance: "critical",
    confidence: "medium",
    nextAction: "Segment discovery conversations by annual experiment volume and compare problem severity and willingness to pay.",
  },
  {
    seedKey: "a021",
    statement: "Companies using multiple experimentation platforms are particularly attractive customers.",
    category: "Customer",
    importance: "high",
    confidence: "high",
    nextAction: "Compare pain, fragmentation and willingness to pay between single-platform and multi-platform organisations.",
  },
  {
    seedKey: "a022",
    statement: "Organisations without an established experimentation programme are poor initial Knomera customers.",
    category: "Customer",
    importance: "high",
    confidence: "high",
    nextAction: "Test the proposition with lower-maturity organisations and compare perceived value.",
  },
  {
    seedKey: "a023",
    statement: "Enterprise experimentation teams will accept another tool if it sits above rather than replaces their existing stack.",
    category: "Customer",
    importance: "critical",
    confidence: "medium",
    nextAction: "Show prospective customers the proposed architecture and explicitly test resistance to adding another platform.",
  },
  {
    seedKey: "a024",
    statement: "Customers want recommendations rather than another dashboard.",
    category: "Customer",
    importance: "critical",
    confidence: "high",
    nextAction: "Compare customer reactions to dashboard-led and recommendation-led prototypes.",
  },
  {
    seedKey: "a025",
    statement: "Teams will trust Knomera to recommend when experiments should run.",
    category: "Customer",
    importance: "critical",
    confidence: "low",
    nextAction: "Produce scheduling recommendations for real experiment roadmaps and compare them with expert human decisions.",
  },
  {
    seedKey: "a026",
    statement: "Teams will eventually allow Knomera to automatically schedule experiments.",
    category: "Customer",
    importance: "medium",
    confidence: "low",
    nextAction: "First validate willingness to use recommendations, then test appetite for increasing levels of automation.",
  },
  {
    seedKey: "a027",
    statement: "Experimentation leaders can justify Knomera's cost through increased experimentation throughput and value.",
    category: "Customer",
    importance: "critical",
    confidence: "medium",
    nextAction: "Build ROI models using real customer experiment volumes, delays and historical experiment value.",
  },
  {
    seedKey: "a028",
    statement: "Traffic can be modelled as a finite experimentation resource.",
    category: "Capacity Engine",
    importance: "critical",
    confidence: "high",
    nextAction: "Build a capacity model using real traffic distributions and historical experiments.",
  },
  {
    seedKey: "a029",
    statement: "Sample-size requirements can be estimated accurately enough for planning purposes.",
    category: "Capacity Engine",
    importance: "critical",
    confidence: "high",
    nextAction: "Back-test predicted sample requirements and durations against completed experiments.",
  },
  {
    seedKey: "a030",
    statement: "Historical effect sizes can help suggest realistic MDEs for future experiments.",
    category: "Capacity Engine",
    importance: "high",
    confidence: "medium",
    nextAction: "Analyse historical experiment effect-size distributions by experiment type and business area.",
  },
  {
    seedKey: "a031",
    statement: "Using a blanket MDE across every experiment produces poor capacity estimates.",
    category: "Capacity Engine",
    importance: "medium",
    confidence: "high",
    nextAction: "Compare capacity forecasts using fixed MDEs with forecasts using context-specific MDE assumptions.",
  },
  {
    seedKey: "a032",
    statement: "Experiment duration estimates do not need to be exact to be operationally useful.",
    category: "Capacity Engine",
    importance: "critical",
    confidence: "medium",
    nextAction: "Give experimentation managers duration ranges and test whether they are sufficient for roadmap planning.",
  },
  {
    seedKey: "a033",
    statement: "Seasonality materially affects future experiment duration.",
    category: "Capacity Engine",
    importance: "high",
    confidence: "high",
    nextAction: "Back-test duration forecasts across high and low traffic periods.",
  },
  {
    seedKey: "a034",
    statement: "Conversion rate alone is insufficient for estimating experiment capacity.",
    category: "Capacity Engine",
    importance: "high",
    confidence: "high",
    nextAction: "Model the contribution of traffic, allocation, baseline rate, MDE and metric variance to duration.",
  },
  {
    seedKey: "a035",
    statement: "Experiment capacity can be calculated at individual surfaces and audiences rather than only at total website level.",
    category: "Capacity Engine",
    importance: "critical",
    confidence: "high",
    nextAction: "Build a prototype traffic topology for a real digital product.",
  },
  {
    seedKey: "a036",
    statement: "Available traffic can be automatically matched to candidate experiments.",
    category: "Capacity Engine",
    importance: "critical",
    confidence: "medium",
    nextAction: "Build a prototype matching algorithm using a real experiment roadmap and traffic topology.",
  },
  {
    seedKey: "a037",
    statement: "Knomera can identify unused capacity where smaller experiments could run.",
    category: "Capacity Engine",
    importance: "medium",
    confidence: "medium",
    nextAction: "Back-test gap identification against historical experiment calendars.",
  },
  {
    seedKey: "a038",
    statement: "Capacity planning can meaningfully increase the number of valid experiments completed per year.",
    category: "Capacity Engine",
    importance: "critical",
    confidence: "medium",
    nextAction: "Simulate historical programmes with and without capacity optimisation, then validate through a customer pilot.",
  },
  {
    seedKey: "a039",
    statement: "Two experiments sharing a page do not automatically need to be mutually exclusive.",
    category: "Experiment Interaction",
    importance: "high",
    confidence: "high",
    nextAction: "Validate against statistical literature, practitioner experience and historical parallel experiments.",
  },
  {
    seedKey: "a040",
    statement: "Experiment interaction risk can be represented using understandable dimensions.",
    category: "Experiment Interaction",
    importance: "high",
    confidence: "high",
    nextAction: "Validate pollution-matrix dimensions with experienced experimentation practitioners.",
  },
  {
    seedKey: "a041",
    statement: "Audience overlap is only one component of experiment interaction risk.",
    category: "Experiment Interaction",
    importance: "high",
    confidence: "high",
    nextAction: "Review interaction examples and identify factors associated with meaningful interference.",
  },
  {
    seedKey: "a042",
    statement: "Shared metrics increase the potential cost of experiment interaction.",
    category: "Experiment Interaction",
    importance: "medium",
    confidence: "medium",
    nextAction: "Model and review historical examples where parallel tests affect the same primary or secondary metrics.",
  },
  {
    seedKey: "a043",
    statement: "UI proximity can be used as one signal of interaction likelihood.",
    category: "Experiment Interaction",
    importance: "medium",
    confidence: "medium",
    nextAction: "Back-test proximity scoring against known experiment interactions.",
  },
  {
    seedKey: "a044",
    statement: "Experiment hypotheses can be used to infer interaction risk.",
    category: "Experiment Interaction",
    importance: "high",
    confidence: "medium",
    nextAction: "Compare hypothesis-based interaction predictions against expert human assessments.",
  },
  {
    seedKey: "a045",
    statement: "A useful pollution score can be generated without observing actual experiment outcomes.",
    category: "Experiment Interaction",
    importance: "high",
    confidence: "medium",
    nextAction: "Blind-test pollution scores against practitioner assessments of real experiment pairs.",
  },
  {
    seedKey: "a046",
    statement: "Teams would run more experiments in parallel if given defensible interaction-risk guidance.",
    category: "Experiment Interaction",
    importance: "critical",
    confidence: "medium",
    nextAction: "Measure planned parallelism before and after introducing risk guidance in a pilot programme.",
  },
  {
    seedKey: "a047",
    statement: "Knomera should recommend mitigation rather than simply classifying experiment combinations as safe or unsafe.",
    category: "Experiment Interaction",
    importance: "high",
    confidence: "high",
    nextAction: "Prototype both approaches and test which better supports practitioner decisions.",
  },
  {
    seedKey: "a048",
    statement: "Some experiment interaction risk is worth accepting because increased throughput can outweigh the statistical risk.",
    category: "Experiment Interaction",
    importance: "critical",
    confidence: "high",
    nextAction: "Build example decision models and validate the trade-off with experienced practitioners.",
  },
  {
    seedKey: "a049",
    statement: "Experiment roadmaps can be represented as a constraint optimisation problem.",
    category: "Scheduling",
    importance: "critical",
    confidence: "high",
    nextAction: "Build a solver prototype using a real experiment roadmap, traffic constraints and dependencies.",
  },
  {
    seedKey: "a050",
    statement: "Planned experiments contain enough predictable attributes to schedule algorithmically.",
    category: "Scheduling",
    importance: "critical",
    confidence: "medium",
    nextAction: "Import several real roadmaps and assess whether required scheduling attributes are available or inferable.",
  },
  {
    seedKey: "a051",
    statement: "Business priority should influence experimentation traffic allocation.",
    category: "Scheduling",
    importance: "high",
    confidence: "high",
    nextAction: "Validate prioritisation inputs with experimentation and product leaders.",
  },
  {
    seedKey: "a052",
    statement: "Experiments need deadlines or scheduling windows as well as priority.",
    category: "Scheduling",
    importance: "high",
    confidence: "high",
    nextAction: "Analyse real roadmaps for launch dependencies, seasonal windows and deadlines.",
  },
  {
    seedKey: "a053",
    statement: "Knomera can suggest a materially better experiment schedule than manual planning.",
    category: "Scheduling",
    importance: "critical",
    confidence: "low",
    nextAction: "Blind-compare Knomera-generated schedules with schedules produced by experienced experimentation leaders.",
  },
  {
    seedKey: "a054",
    statement: "Re-planning when experiments finish earlier or later than expected provides meaningful value.",
    category: "Scheduling",
    importance: "high",
    confidence: "medium",
    nextAction: "Simulate dynamic re-planning against historical experiment completion dates.",
  },
  {
    seedKey: "a055",
    statement: "Teams will allow software to recommend moving experiment roadmap items.",
    category: "Scheduling",
    importance: "high",
    confidence: "medium",
    nextAction: "Present recommendation-based roadmap changes to practitioners and observe acceptance or override behaviour.",
  },
  {
    seedKey: "a056",
    statement: "\"What should we run next?\" is ultimately more valuable than simply answering \"when will this experiment finish?\"",
    category: "Scheduling",
    importance: "critical",
    confidence: "medium",
    nextAction: "Test both propositions separately in customer discovery and prototype sessions.",
  },
  {
    seedKey: "a057",
    statement: "Experiment results become significantly less discoverable over time.",
    category: "Knowledge",
    importance: "high",
    confidence: "high",
    nextAction: "Run retrieval exercises across historical experiment repositories.",
  },
  {
    seedKey: "a058",
    statement: "Existing experiment repositories capture results better than reusable learnings.",
    category: "Knowledge",
    importance: "high",
    confidence: "high",
    nextAction: "Audit experiment documentation and distinguish stored results from reusable knowledge.",
  },
  {
    seedKey: "a059",
    statement: "A reusable learning should be represented separately from an individual experiment result.",
    category: "Knowledge",
    importance: "critical",
    confidence: "high",
    nextAction: "Model historical experiments into separate experiment, result and learning objects and test usability.",
  },
  {
    seedKey: "a060",
    statement: "Multiple experiments can contribute evidence towards one business belief.",
    category: "Knowledge",
    importance: "critical",
    confidence: "high",
    nextAction: "Model a real historical experimentation programme as beliefs supported by multiple experiments.",
  },
  {
    seedKey: "a061",
    statement: "Knomera can build an evolving representation of what a company knows.",
    category: "Knowledge",
    importance: "critical",
    confidence: "medium",
    nextAction: "Prototype a knowledge model using historical experimentation data from a real organisation.",
  },
  {
    seedKey: "a062",
    statement: "Historical knowledge should influence future experiment prioritisation.",
    category: "Knowledge",
    importance: "critical",
    confidence: "high",
    nextAction: "Compare prioritisation decisions with and without access to structured historical learning.",
  },
  {
    seedKey: "a063",
    statement: "AI can extract useful structured learnings from existing experiment documentation.",
    category: "Knowledge",
    importance: "high",
    confidence: "medium",
    nextAction: "Benchmark AI extraction against expert human labelling of historical experiment documentation.",
  },
  {
    seedKey: "a064",
    statement: "Teams will permit Knomera to ingest historical experiment documentation.",
    category: "Knowledge",
    importance: "critical",
    confidence: "medium",
    nextAction: "Explore security, privacy and procurement requirements during customer discovery.",
  },
  {
    seedKey: "a065",
    statement: "Knomera's knowledge asset becomes more valuable as the platform is used for longer.",
    category: "Knowledge",
    importance: "critical",
    confidence: "medium",
    nextAction: "Define measurable indicators of knowledge reuse and test longitudinally with early customers.",
  },
  {
    seedKey: "a066",
    statement: "Accumulated company knowledge can create meaningful switching costs.",
    category: "Knowledge",
    importance: "high",
    confidence: "low",
    nextAction: "Revisit after longitudinal customer usage exists and test whether accumulated knowledge affects retention.",
  },
  {
    seedKey: "a067",
    statement: "LLMs can understand experiment hypotheses sufficiently well for useful classification.",
    category: "AI",
    importance: "high",
    confidence: "medium",
    nextAction: "Benchmark LLM classification against expert-labelled experiment hypotheses.",
  },
  {
    seedKey: "a068",
    statement: "AI can map experiments to business areas automatically.",
    category: "AI",
    importance: "high",
    confidence: "medium",
    nextAction: "Create a labelled historical dataset and measure classification accuracy.",
  },
  {
    seedKey: "a069",
    statement: "AI can identify semantically related historical experiments.",
    category: "AI",
    importance: "high",
    confidence: "high",
    nextAction: "Build a retrieval benchmark using known related and unrelated experiment pairs.",
  },
  {
    seedKey: "a070",
    statement: "AI-generated experiment ideas alone are not differentiated enough to build Knomera around.",
    category: "AI",
    importance: "high",
    confidence: "high",
    nextAction: "Track competitor capabilities and test customer willingness to pay specifically for idea generation.",
  },
  {
    seedKey: "a071",
    statement: "Business context makes AI experimentation recommendations materially better.",
    category: "AI",
    importance: "critical",
    confidence: "medium",
    nextAction: "Compare generic recommendations with recommendations generated using structured company context.",
  },
  {
    seedKey: "a072",
    statement: "Customers will tolerate occasional imperfect recommendations if Knomera explains its reasoning.",
    category: "AI",
    importance: "high",
    confidence: "low",
    nextAction: "Test transparent and opaque recommendations with practitioners and measure trust and acceptance.",
  },
  {
    seedKey: "a073",
    statement: "Recommendations need supporting evidence rather than unexplained AI output.",
    category: "AI",
    importance: "critical",
    confidence: "high",
    nextAction: "Compare practitioner responses to recommendations with and without supporting evidence.",
  },
  {
    seedKey: "a074",
    statement: "Human override will remain important for high-impact experimentation planning decisions.",
    category: "AI",
    importance: "high",
    confidence: "high",
    nextAction: "Validate desired automation boundaries during prototype testing.",
  },
  {
    seedKey: "a075",
    statement: "Knomera's defensible asset is the business model and data layer rather than the underlying LLM.",
    category: "AI",
    importance: "critical",
    confidence: "high",
    nextAction: "Continue competitor and architecture analysis while testing whether accumulated context improves product value.",
  },
  {
    seedKey: "a076",
    statement: "Knomera should sit above experimentation platforms rather than replace them.",
    category: "Product & Integration",
    importance: "critical",
    confidence: "high",
    nextAction: "Test this positioning explicitly in customer interviews and sales conversations.",
  },
  {
    seedKey: "a077",
    statement: "Customers will connect their existing experimentation platforms to Knomera.",
    category: "Product & Integration",
    importance: "critical",
    confidence: "medium",
    nextAction: "Ask design partners to authorise a real integration or provide equivalent exported data.",
  },
  {
    seedKey: "a078",
    statement: "Initial customer value can be delivered before deep platform integrations exist.",
    category: "Product & Integration",
    importance: "critical",
    confidence: "medium",
    nextAction: "Attempt to deliver and sell a concierge or manually imported MVP.",
  },
  {
    seedKey: "a079",
    statement: "CSV or manual import is acceptable for an early Knomera pilot.",
    category: "Product & Integration",
    importance: "high",
    confidence: "medium",
    nextAction: "Run an early pilot using manual or CSV ingestion and measure friction.",
  },
  {
    seedKey: "a080",
    statement: "Automatic traffic and analytics ingestion will eventually be required.",
    category: "Product & Integration",
    importance: "high",
    confidence: "high",
    nextAction: "Observe data-maintenance effort and failure points during early pilots.",
  },
  {
    seedKey: "a081",
    statement: "Analytics platforms contain enough traffic information for much of the capacity model.",
    category: "Product & Integration",
    importance: "critical",
    confidence: "medium",
    nextAction: "Build a technical spike using real analytics exports or APIs.",
  },
  {
    seedKey: "a082",
    statement: "Experimentation platforms contain enough metadata to bootstrap Knomera's experiment model.",
    category: "Product & Integration",
    importance: "high",
    confidence: "medium",
    nextAction: "Review APIs and exports from major experimentation platforms against Knomera's required fields.",
  },
  {
    seedKey: "a083",
    statement: "Project-management integrations become useful once scheduling is established.",
    category: "Product & Integration",
    importance: "medium",
    confidence: "medium",
    nextAction: "Map customer roadmap workflows and identify where Jira, Linear or similar systems become necessary.",
  },
  {
    seedKey: "a084",
    statement: "Customers do not want to manually maintain another experiment repository.",
    category: "Product & Integration",
    importance: "critical",
    confidence: "high",
    nextAction: "Observe willingness to maintain duplicated experiment records during prototype and pilot use.",
  },
  {
    seedKey: "a085",
    statement: "Knomera needs to fit existing experimentation workflows rather than require customers to adopt an entirely new process.",
    category: "Product & Integration",
    importance: "critical",
    confidence: "high",
    nextAction: "Map existing workflows before designing integration and onboarding requirements.",
  },
  {
    seedKey: "a086",
    statement: "Companies will pay specifically for experimentation intelligence and orchestration.",
    category: "Commercial",
    importance: "critical",
    confidence: "low",
    nextAction: "Put a priced Knomera proposition in front of qualified prospective customers and ask for the sale.",
  },
  {
    seedKey: "a087",
    statement: "Knomera can deliver enough value to charge customers before becoming a fully automated SaaS product.",
    category: "Commercial",
    importance: "critical",
    confidence: "medium",
    nextAction: "Attempt to sell a concierge or design-partner engagement before full product automation exists.",
  },
  {
    seedKey: "a088",
    statement: "A paid pilot is preferable to a free design partnership for validating commercial demand.",
    category: "Commercial",
    importance: "high",
    confidence: "medium",
    nextAction: "Test paid and free design-partner propositions and compare engagement and conversion.",
  },
  {
    seedKey: "a089",
    statement: "Knomera can demonstrate financial value through increased experimentation throughput.",
    category: "Commercial",
    importance: "critical",
    confidence: "medium",
    nextAction: "Build ROI models using customer traffic, throughput, delay and experiment-value data.",
  },
  {
    seedKey: "a090",
    statement: "Preventing poor or low-value experiments creates measurable customer value.",
    category: "Commercial",
    importance: "high",
    confidence: "medium",
    nextAction: "Quantify the traffic, time and opportunity cost consumed by experiments that should not have run.",
  },
  {
    seedKey: "a091",
    statement: "Enterprise pricing can be materially higher than conventional CRO tooling add-ons.",
    category: "Commercial",
    importance: "high",
    confidence: "low",
    nextAction: "Test pricing ranges in customer conversations and through real commercial proposals.",
  },
  {
    seedKey: "a092",
    statement: "Per-seat pricing would align poorly with Knomera's customer value.",
    category: "Commercial",
    importance: "medium",
    confidence: "high",
    nextAction: "Compare customer reactions and economics across seat-based and value/scale-based pricing models.",
  },
  {
    seedKey: "a093",
    statement: "Pricing based on experimentation scale or capability may align better with customer value.",
    category: "Commercial",
    importance: "high",
    confidence: "medium",
    nextAction: "Test packaging based on experiment volume, traffic, business units or capability level.",
  },
  {
    seedKey: "a094",
    statement: "A \u00a310,000 to \u00a330,000 initial engagement is plausible before Knomera has a mature SaaS product.",
    category: "Commercial",
    importance: "critical",
    confidence: "low",
    nextAction: "Put proposals within this range in front of qualified prospects and record the response.",
  },
  {
    seedKey: "a095",
    statement: "Consulting can fund product development without Knomera becoming primarily a consultancy.",
    category: "Commercial",
    importance: "high",
    confidence: "medium",
    nextAction: "Track service hours, gross margin, reusable product development and revenue across initial engagements.",
  },
  {
    seedKey: "a096",
    statement: "Founder expertise materially increases early Knomera sales credibility.",
    category: "Commercial",
    importance: "high",
    confidence: "high",
    nextAction: "Track customer engagement and conversion during founder-led discovery and sales.",
  },
  {
    seedKey: "a097",
    statement: "Knomera can eventually sell independently of founder reputation.",
    category: "Commercial",
    importance: "critical",
    confidence: "low",
    nextAction: "Test non-founder-led acquisition and sales once a repeatable proposition has been established.",
  },
  {
    seedKey: "a098",
    statement: "Major experimentation vendors will continue adding AI capabilities.",
    category: "Competitive",
    importance: "critical",
    confidence: "high",
    nextAction: "Review major competitor product announcements and roadmaps quarterly.",
  },
  {
    seedKey: "a099",
    statement: "Generic AI experiment generation will rapidly commoditise.",
    category: "Competitive",
    importance: "high",
    confidence: "high",
    nextAction: "Track feature convergence across experimentation, analytics and general AI products.",
  },
  {
    seedKey: "a100",
    statement: "Existing experimentation vendors have an advantage because they already possess customer experiment data.",
    category: "Competitive",
    importance: "critical",
    confidence: "high",
    nextAction: "Analyse competitor access to experiment history, results, audiences and traffic data.",
  },
  {
    seedKey: "a101",
    statement: "Existing vendors are disadvantaged because they primarily understand experiments inside their own platform rather than the customer's complete business context.",
    category: "Competitive",
    importance: "critical",
    confidence: "medium",
    nextAction: "Compare competitor data models and integrations with the wider context required by Knomera's proposed recommendations.",
  },
  {
    seedKey: "a102",
    statement: "Cross-platform neutrality can be a meaningful Knomera advantage.",
    category: "Competitive",
    importance: "critical",
    confidence: "medium",
    nextAction: "Test the proposition specifically with organisations operating multiple experimentation platforms.",
  },
  {
    seedKey: "a103",
    statement: "Customers value an independent experimentation intelligence layer across their stack.",
    category: "Competitive",
    importance: "critical",
    confidence: "low",
    nextAction: "Test willingness to adopt and pay for an independent layer rather than relying on existing vendors.",
  },
  {
    seedKey: "a104",
    statement: "Knomera's moat cannot simply be better AI.",
    category: "Competitive",
    importance: "critical",
    confidence: "high",
    nextAction: "Continue evaluating differentiation against improving foundation models and competitor AI capabilities.",
  },
  {
    seedKey: "a105",
    statement: "The combination of business topology, experiment history, constraints and accumulated learnings could become a defensible Knomera asset.",
    category: "Competitive",
    importance: "critical",
    confidence: "medium",
    nextAction: "Test whether recommendations measurably improve as increasingly rich company context is accumulated.",
  },
  {
    seedKey: "a106",
    statement: "Jon and Ahmed can build a credible Knomera MVP without external engineering hires.",
    category: "Founder & Execution",
    importance: "high",
    confidence: "high",
    nextAction: "Deliver the first usable MVP and track where capability or capacity gaps emerge.",
  },
  {
    seedKey: "a107",
    statement: "Founder experimentation expertise compensates for initially limited product breadth.",
    category: "Founder & Execution",
    importance: "high",
    confidence: "high",
    nextAction: "Test customer response to a narrow product combined with expert founder-led onboarding and interpretation.",
  },
  {
    seedKey: "a108",
    statement: "Three months is enough to reach something demonstrable to prospective customers.",
    category: "Founder & Execution",
    importance: "high",
    confidence: "medium",
    nextAction: "Define the three-month demonstration milestone and track actual delivery against it.",
  },
  {
    seedKey: "a109",
    statement: "A first commercial contract could cover Ahmed's subsequent development costs.",
    category: "Founder & Execution",
    importance: "critical",
    confidence: "low",
    nextAction: "Define the required contract value and build a qualified pipeline capable of producing it.",
  },
  {
    seedKey: "a110",
    statement: "Building substantial product functionality before customer discovery creates a significant risk of wasted development.",
    category: "Founder & Execution",
    importance: "critical",
    confidence: "high",
    nextAction: "Require major roadmap items to link to a validated customer problem or explicit assumption being tested.",
  },
  {
    seedKey: "a111",
    statement: "Founder access to senior experimentation practitioners provides Knomera with a strong initial discovery channel.",
    category: "Founder & Execution",
    importance: "high",
    confidence: "high",
    nextAction: "Secure the first 10 to 15 structured discovery conversations through the founders' existing networks.",
  },
  {
    seedKey: "a112",
    statement: "Experience from individual companies provides useful problem insight but creates a risk of overfitting Knomera to one sophisticated experimentation organisation.",
    category: "Founder & Execution",
    importance: "critical",
    confidence: "high",
    nextAction: "Validate every foundational problem across multiple unrelated organisations, industries and experimentation setups.",
  },
];
